// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using marketplace.Data;

namespace marketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210606184731_AddProductSeed")]
    partial class AddProductSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("marketplace.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Product-001",
                            CreatedOn = new DateTimeOffset(new DateTime(2021, 6, 6, 18, 47, 31, 513, DateTimeKind.Unspecified).AddTicks(1426), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Product 1",
                            Price = 10.25m
                        },
                        new
                        {
                            Id = 2,
                            Code = "Product-002",
                            CreatedOn = new DateTimeOffset(new DateTime(2021, 6, 6, 18, 47, 31, 513, DateTimeKind.Unspecified).AddTicks(2385), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Product 2",
                            Price = 45m
                        },
                        new
                        {
                            Id = 3,
                            Code = "Product-003",
                            CreatedOn = new DateTimeOffset(new DateTime(2021, 6, 6, 18, 47, 31, 513, DateTimeKind.Unspecified).AddTicks(2401), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Product 3",
                            Price = 9.25m
                        },
                        new
                        {
                            Id = 4,
                            Code = "Product-004",
                            CreatedOn = new DateTimeOffset(new DateTime(2021, 6, 6, 18, 47, 31, 513, DateTimeKind.Unspecified).AddTicks(2402), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Product 4",
                            Price = 3.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
